#!/usr/bin/fish
function menu_command
  fzf --no-sort --no-hscroll --cycle --reverse --prompt=" ◇"\t --tabstop=4 \
      --delimiter=\t --nth=2 --with-nth=1..2 \
      --print-query
end

function choose
  grep -v "^#\|^\s*\$" $argv  \
  | sed "s/\s*:\s*/\t/g"      \
  | menu_command
end

set -l choice (choose < ~/apps/launcher-list)
set choose_status $status
if [ $choose_status -eq 1 -a -n "$choice" ]
  # no match - run query string as command
  set cmd $choice[1]
else if [ $choose_status -ne 0 ]
  # error
  exit $choose_status
else
  set cmd (echo $choice[2] | cut -f3)
  set cmd $cmd
end

status job-control full
eval $cmd \& \; disown

