#!/usr/bin/env dash
# vim: ft=sh:
TAB=$(printf '\t')
THIS_SH=$(head -1 "$0" | sed "s/^#!//")

menu_command() {
  fzf --no-sort --no-hscroll --cycle --reverse --prompt=" ◇$TAB" --tabstop=4 \
      --delimiter="$TAB" --nth=2 --with-nth=1..2 \
      --print-query
}

choose() {
  grep -v "^#\|^\s*\$"   \
  | sed "s/\s*:\s*/\t/g" \
  | menu_command
}

CHOICE=$(choose < ~/apps/launcher-list)
CHOOSE_STATUS="$?"

QUERY=$(echo "$CHOICE" | head -n 1)
COMMAND=$(echo "$CHOICE" | tail -n 1 | cut -f3)

COMMAND=$(
  if (test "$CHOOSE_STATUS" -eq 1 && test -n "$CHOICE"); then
    printf "%s\n" "$QUERY" # no match - run query string as command
  elif test "$CHOOSE_STATUS" -ne 0; then
    echo # error
  else
    printf "%s\n" "$COMMAND"
  fi
)

nohup $THIS_SH -c "$COMMAND &" <&- >&- 2>&-

