#!/usr/bin/env bash
# vim: ft=sh:

# simple launcher menu

set -euo pipefail

menu() {
    hs
}

choose() {
    grep -v "^#\|^\s*\$" | \
    sed "s/\s*:\s*/\t/g" | \
    menu
}

if COMMAND=$(choose < ~/apps/launcher-list-2); then
    swaymsg exec -- $COMMAND
else
    exit 1
fi

