#!/usr/bin/fish
set -g lock_dir /run/user/(id -u)/app-menu.lock.d

if mkdir "$lock_dir"
  function cleanup -p %self
    rm -rf "$lock_dir"
  end
  echo %self > "$lock_dir/pid"
  term --class rk-pop-up -d 80 20 -e app-menu-term
else
  exit 1
end

