#!/bin/sh
# vim: lbr:

cd

header() {
  echo "Backing up: "
  while test "$#" -ne 0; do
    echo "$1"
    shift
  done
  echo
}

go() {
  header "$@"
  borg --progress create --stats --verbose --one-file-system "::{user}@{hostname}-{utcnow}" "$@" \
    --exclude-caches \
    --exclude ".config/discord/Cache" \
    --exclude-if-present ".rustc_info.json" \
    --exclude "*/dist-newstyle" \
    --exclude "*/dist" \
    --exclude "*/obj" \
    --exclude "*/debug" \
    --exclude "*/release" \
    --exclude "*/__pycache__" \
    --exclude "*/bin" \
    --exclude "*.a" \
    --exclude "*.o" \
    --exclude "*.so" \
    --exclude "*.rlib" \
    --exclude "*.hi"
}

DIRS="apps/ comics/ .config/ documents/ film/recorded/ .gnupg/ misc/ .password-store/ pictures/ projects/ shares/ .ssh/"
go $DIRS "$@"

