#!/bin/sh
# vim: lbr:

header() {
  echo "Backing up: "
  while test "$#" -ne 0; do
    echo "$1"
    shift
  done
  echo
}

go() {
  header "$@"
  borg -p create --stats --verbose --one-file-system "::{user}@{hostname}-{utcnow}" "$@"
}

DIRS="apps/ comics/ .config/ documents/ .gnupg/ misc/ .password-store/ pictures/ projects/ shares/ .ssh/"
go $DIRS "$@"

