#!/bin/sh
borg -p create --stats --verbose --one-file-system \
"::{user}@{hostname}-{utcnow}" \
apps/ comics/ .config/ disc-images/ documents/ film/ .gnupg/ misc/ music/ .password-store/ \
pictures/ projects/ shares/ .ssh/

