#!/usr/bin/env bash
# vim: ft=sh:

# show password-store selection menu

set -euo pipefail

cd "${PASSWORD_STORE_DIR:-${HOME}/.password-store}"

CHOICE="$( \
    find . -path "*/\.*" -prune -o -type f -print | \
    sed "s#^\./##; s/\.gpg\$//;" | \
    fzf --no-hscroll --cycle --reverse --prompt="🔑 " \
)"

pass show -c "${CHOICE}"
notify-send "pass: ${CHOICE}" \
    "$(pass show "${CHOICE}" | tail -n +2)"

