#!/usr/bin/env dash
# vim: ft=sh:
test -d "$PASSWORD_STORE_DIR" \
  && cd "$PASSWORD_STORE_DIR" \
  || cd ~/.password-store

CHOICE=$( \
    find . -path "*/\.*" -prune -o -type f -print \
  | sed "s#^\./##; s/\.gpg\$//;" \
  | fzf --no-hscroll --cycle --reverse --prompt="🔑 " \
) && {
    CONTENT=$(pass "${CHOICE}" $@) && {
        echo "${CONTENT}" | head -1 | nohup wl-copy -o -n >&- 2>&- &
        notify-send "pass: ${CHOICE}" "$(echo "${CONTENT}" | awk -v RS= 'NR > 1 {print}')"
    }
}

