#!/usr/bin/env dash
# vim: ft=sh:
LOCK_DIR="/run/user/$(id -u)/term-tool.lock.d"
FIFO="${LOCK_DIR}/fifo"
TERMOPTS="--class rk-pop-up -d 60 20"
THIS_SH=$(head -1 "$0" | sed "s/^#!//")

test "$#" -ge 1 || exit 1

cleanup() {
  rm -rf "${LOCK_DIR}"
}

if mkdir "${LOCK_DIR}"; then
  trap cleanup INT

  if mkfifo "${FIFO}"; then
    term ${TERMOPTS} -e ${THIS_SH} -c "$* >${FIFO} 2>/dev/tty <&-" &
    cat "${FIFO}"
  fi

  cleanup
fi

